server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          #  配置git仓库
          uri: git@github.com:RicharDKcoder/zoo.git
          force-pull: true
          search-paths: zoo-config/config/
