server:
  port: 8201
spring:
  application:
    name: microservice-server-zuul

zuul:
  host:
    connect-timeout-millis: 30000
    socket-timeout-millis: 30000

hystrix:
  command:
    myusers-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000

eureka:
  client:
    serviceUrl:
      #  注册到eureka集群
      defaultZone: http://eureka8101:8101/eureka/,http://eureka8102:8102/eureka/,http://eureka8103:8103/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}}