server:
  port: 8101

spring:
  application:
    name: microservice-server-config
  cloud:
    config:
      server:
        git:
          #  配置git仓库
          uri: git@github.com:RicharDKcoder/zoo.git
          force-pull: true
          search-paths: zoo-server-config/config/

eureka:
  client:
    serviceUrl:
      #  注册到eureka集群
      defaultZone: http://eureka8001:8001/eureka/,http://eureka8002:8002/eureka/,http://eureka8003:8003/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
