spring:
  application:
    name: microservice-server-eureka
  profiles:
    active: stand-alone

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka8001:8001/eureka/,http://eureka8002:8002/eureka/,http://eureka8003:8003/eureka/
  instance:
    prefer-ip-address: true

---
spring:
  profiles: stand-alone

server:
  port: 8001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://eureka8001:8001/eureka/

---
spring:
  profiles: eureka8001

server:
  port: 8001

eureka:
  instance:
    hostname: eureka8001

---
spring:
  profiles: eureka8002

server:
  port: 8002

eureka:
  instance:
    hostname: eureka8002

---
spring:
  profiles: eureka8003

server:
  port: 8003

eureka:
  instance:
    hostname: eureka8003
