server:
  port: 8301

spring:
  application:
    name: microservice-server-customer

eureka:
  client:
    serviceUrl:
      #  注册到eureka集群
      defaultZone: http://eureka8101:8101/eureka/,http://eureka8102:8102/eureka/,http://eureka8103:8103/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}

feign:
  client:
    config:
      default:
        connectTimeout: 50000
        readTimeout: 50000
        loggerLevel: full

hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          timeoutInMilliseconds: 600000

ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 30000
